import { Box } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as React from 'react';
import anime from 'animejs';
import useDidMountEffect from './hooks/useMountEffect'


const Line = () => {
  return (
    <Box sx={{ width: "100px", height: "3px", backgroundColor: "white" }}></Box>
  )
}

var i = 0;
const Character = () => {
  const [jumpRef, set] = React.useState<any>(null);
  const animationEnded = React.useRef(true)
  function animationFinished() { 
    animationEnded.current = true
  }

  
  React.useEffect(() => {
    const body = document.body;

    body.addEventListener('keypress', (e) => {
      if (e.key === "w" && animationEnded.current === true) {  //checks the key and if the animation has ended and then proceeds
          animationEnded.current = false     
          set(anime({  //JUMPING ANIMATION
            targets: '.el',
            translateY: -120,
            duration: 500,
            easing: 'easeOutElastic(1, .8)',
            direction: 'alternate',
        }).finished.then(animationFinished)
        )
      } else if (e.key === "d" && animationEnded.current === true) {        
        animationEnded.current = false 
        i += 250
        set(anime({ //moving animation
              targets: '.el',
              translateX: 250 + i,
              duration: 500,
              easing: 'easeInOutExpo'
            }).finished.then(animationFinished)
        )
      }
    })
  }, [])
  
  return (
      <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg" className='el' width="15vw" height="5vw">
        <path fill="#FF0066" d="M54.4,-27C66.1,-11.1,68.1,14.7,57.4,32.1C46.8,49.6,23.4,58.7,2.6,57.2C-18.1,55.7,-36.3,43.5,-43.8,27.9C-51.3,12.3,-48.2,-6.9,-39.1,-21.2C-30,-35.6,-15,-45.2,3.2,-47C21.3,-48.9,42.7,-42.9,54.4,-27Z" transform="translate(100 100)" />
      </svg>
  )
}

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Multi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ width: "100vw", border: "1px solid white", height: "30vw" }}>
        <Line />
        <Box sx={{ position: 'absolute', top: "50%"}}>
          <Character/>
        </Box>
      </Box>
    </Box>
  )
}

export default Home
